name = "altianly-ai"
main = "index.js"
compatibility_date = "2026-06-21"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "ALTIANLY_DATA"
id = "5c5e455f39a84c71b83eb38bb2643e58"
preview_id = "5c5e455f39a84c71b83eb38bb2643e58"

[vars]
RP_ORIGIN = "http://localhost:8081"
